#!/bin/sh
#
#   http://code.google.com/media-translate/
#   Copyright (C) 2010  Serge A. Timchenko
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.
#

local DATAPATH=$BASEPATH/app/shoutcast
cd $DATAPATH

. ./settings

local CHANNELFILE="$CACHEPATH/shoutcast.genrelist.cache"
local TEMPDL=$TMPFILE.dl

local TIMELIFE=1200

let tsttime=`date +%s`-$TIMELIFE

local REFRESHCACHE=yes
if [ -f "$CHANNELFILE" ]; then
  if [ "`ls -s "$CHANNELFILE" | awk '{print $1}'`" != "0" ]; then
    if [ `date +%s -r "$CHANNELFILE"` -gt $tsttime ]; then
      REFRESHCACHE=
    fi
  fi
fi

if [ $REFRESHCACHE ]; then
  $WGET -q -O "$TEMPDL" --header "User-Agent: $USERAGENT" ${SHOUTCAST_U}genrelist${SHOUTCAST_K}
  if [ -f "$TEMPDL" ]; then
    if [ "`ls -s "$TEMPDL" | awk '{print $1}'`" != "0" ]; then
      if [ -x "$XSLTPROC" ]; then
        $XSLTPROC --stringparam translate_base_url "$TRANSLATE_CGI" genrelist.xslt "$TEMPDL" | sed '1d' > $CHANNELFILE.tmp
      else
        awk -v translate_base_url="$TRANSLATE_CGI" -f getxml.awk  -f genrelist.awk "$TEMPDL" > $CHANNELFILE.tmp
      fi
      if [ "`ls -s "$CHANNELFILE.tmp" | awk '{print $1}'`" != "0" ]; then 
        mv -f $CHANNELFILE.tmp $CHANNELFILE
      else
        rm -f $CHANNELFILE.tmp
      fi
    fi
    rm -f "$TEMPDL"
  fi
fi

if [ -f "$CHANNELFILE" ]; then
  (
    export BASEPATH;
    export CHANNELFILE;
    template2rss genrelist.xml | printContent "application/rss+xml"
  )
fi