#!/bin/sh
#
#   http://code.google.com/media-translate/
#   Copyright (C) 2010  Serge A. Timchenko
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.
#

local DATAPATH=$BASEPATH/app/radiotime
cd $DATAPATH

. ./settings

local OPML=$TMPFILE.opml
local CHANNELFILE=$TMPFILE.channel

$WGET -q -O "$OPML" "http://opml.radiotime.com/Browse.ashx?c=index,best&locale=${RT_LOCALE}&formats=${RT_FORMATS}&partnerId=${RT_PARTNERID}&serial=${RT_SERIAL}"

if [ -f "$OPML" ]; then
  if [ -x "$XSLTPROC" ]; then
    $XSLTPROC index.xslt "$OPML" | sed '1d' > $CHANNELFILE
  else
    awk -f getxml.awk -f index.awk "$OPML" > $CHANNELFILE
  fi

  (
    export BASEPATH;
    export CHANNELFILE;
    template2rss index.xml | printContent "application/rss+xml"
    rm -f "$CHANNELFILE"
    rm -f "$OPML"
  )
fi