#!/bin/sh
#
#   http://code.google.com/media-translate/
#   Copyright (C) 2010  Serge A. Timchenko
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.
#

local DATAPATH=$BASEPATH/app/tvigle
cd $DATAPATH

get_opt "Channel"
local CHANNEL="$opt"

[ -z "$CHANNEL" ] && return 0

get_opt "Title"
local TITLE="$opt"

local CHANNELFILE="$CACHEPATH/tvigle.$CHANNEL.cache"
local CHANNELXML=$TMPFILE.xml

TIMELIFE=21600

let tsttime=`date +%s`-$TIMELIFE

REFRESHCACHE=yes
if [ -f "$CHANNELFILE" ]; then
  if [ `date +%s -r "$CHANNELFILE"` -gt $tsttime ]; then
    REFRESHCACHE=
  fi
fi

if [ $REFRESHCACHE ]; then
  $MSDL -q -o "$CHANNELXML" -p http --useragent "$USERAGENT" "http://www.tvigle.ru/xml/multi.php?cnl=${CHANNEL}"
  if [ -f "$CHANNELXML" ]; then
    if [ "`ls -s "$CHANNELXML" | awk '{print $1}'`" != "0" ]; then
    [ -z "$TITLE" ] && TITLE="TViGLE Channel: $CHANNEL"
      if [ -x "$XSLTPROC" ]; then
        $XSLTPROC --stringparam title "$TITLE" multi.xslt "$CHANNELXML" | sed '1d' > $CHANNELFILE
      else
        awk -v title="`escapeXML \"$TITLE\"`" -f getxml.awk -f multi.awk "$CHANNELXML" > $CHANNELFILE
      fi
    fi
    rm -f "$CHANNELXML"
  fi
fi

if [ -f "$CHANNELFILE" ]; then
(
  export BASEPATH;
  export CHANNELFILE;
  template2rss multi.xml | printContent "application/rss+xml"
)
fi
