#!/bin/sh
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.
#


ask_url=`echo $arg_opt | awk '{print "http://www.mitele.telecinco.es/services/tk.php?provider=level3&protohash=/CDN/videos/"substr($0,3,3)"/"$0".mp4"}'`

stream_url=`$MSDL -q -p http -o - "${ask_url}" | sed 's-&-&amp\;-g'`

cat > $TMPFILE <<EOF
<?xml version='1.0' encoding="UTF-8" ?><data><url>
EOF

echo $stream_url >> $TMPFILE

cat >> $TMPFILE <<EOF
</url></data>
EOF

cat $TMPFILE && rm -f $TMPFILE

