#!/bin/sh
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.
#

local DATAPATH=$BASEPATH/app/rtvv
cd $DATAPATH

CURPAGE=`echo $arg_url | sed 's-^.*page=--;s-".*--'`

$MSDL -q -p http -o - "${arg_url}" > $TMPFILE
TOTAL_ITEMS=`cat $TMPFILE | grep '<p class="index">' | sed 's-^.*"to">--;s-<.*--'`

(
  export BASEPATH;
  export CURPAGE;
  export TOTAL_ITEMS;
  template2rss ${arg_opt:-index1}.xml | printContent "application/rss+xml"
)
