#!/bin/sh

local DATAPATH=$BASEPATH/app/rtvv
cd $DATAPATH

TEMPFEED=$CACHEPATH/mediafeed.rss
ITEMSFILE=$TMPFILE.items

$MSDL -q -p http -o - "${arg_url}" > $TMPFILE

xml_url=`cat $TMPFILE | grep 'file: "' | sed 's-^.*file: "-http://www\.rtvv\.es-1;s-".*--'`

$MSDL -q -p http -o - "${xml_url}" > $TMPFILE
$XSLTPROC --encoding utf-8 playlist.xslt $TMPFILE 2>/dev/null | sed '1d' >> $ITEMSFILE

rm -f $TMPFILE

cat > $TEMPFEED <<EOF
<?xml version='1.0' encoding="UTF-8" ?>
<rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/">

<script>
	translate_base_url  = "http://127.0.0.1/cgi-bin/translate?";

	storagePath             = getStoragePath("tmp");
	storagePath_stream      = storagePath + "stream.dat";

	itemCount = getPageInfo("itemCount");
	cur_idx = 0;

	while (cur_idx &lt; itemCount)
	{
		request_url = getItemInfo(cur_idx, "link");
		stream_title = getItemInfo(cur_idx, "title");
		translateURL = translate_base_url+"stream,Content-type:video/mp4;,"+request_url;
		streamArray = null;
		streamArray = pushBackStringArray(streamArray, request_url);
		streamArray = pushBackStringArray(streamArray, "");
		streamArray = pushBackStringArray(streamArray, request_url);
		streamArray = pushBackStringArray(streamArray, translateURL);
		streamArray = pushBackStringArray(streamArray, "video/mp4");
		streamArray = pushBackStringArray(streamArray, stream_title);
		streamArray = pushBackStringArray(streamArray, "1");
		writeStringToFile(storagePath_stream, streamArray);
		doModalRss("rss_file://../etc/translate/rss/xspf/videoRenderer.rss");
		cur_idx += 1;
	}
	postMessage("return");
</script>

<mediaDisplay name="threePartsView">
	<idleImage> ./image/POPUP_LOADING_01.png </idleImage>
	<idleImage> ./image/POPUP_LOADING_02.png </idleImage>
	<idleImage> ./image/POPUP_LOADING_03.png </idleImage>
	<idleImage> ./image/POPUP_LOADING_04.png </idleImage>
	<idleImage> ./image/POPUP_LOADING_05.png </idleImage>
	<idleImage> ./image/POPUP_LOADING_06.png </idleImage>
	<idleImage> ./image/POPUP_LOADING_07.png </idleImage>
	<idleImage> ./image/POPUP_LOADING_08.png </idleImage>

	<previewWindow windowColor="0:0:0" offsetXPC="0" widthPC="100" offsetYPC="0" heightPC="100"/>

	<onUserInput>
		userInput = currentUserInput();
		if( "pagedown" == userInput )
		{
			if( (1 + cur_idx) &lt; itemCount )
				playItemURL(-1, 1);
		}
		else if( "pageup" == userInput )
		{
			if( cur_idx &gt; 0 )
				cur_idx -= 2;
			playItemURL(-1, 1);
		}
		else if( "video_stop" == userInput )
		{
			cur_idx = itemCount;
			playItemURL(-1, 1);
		}
	</onUserInput>

</mediaDisplay>

<channel>
EOF

cat $ITEMSFILE >> $TEMPFEED

cat >> $TEMPFEED <<EOF
</channel>
</rss>
EOF

rm -f $ITEMSFILE

printContent "application/rss+xml" "$TEMPFEED"

