#!/bin/sh
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.
#

local DATAPATH=$BASEPATH/app/tve
cd $DATAPATH

local ITEMSFILE=$TMPFILE.items

$MSDL -q -p http -o - "${arg_url}" > $TMPFILE

$XSLTPROC --encoding utf-8 --html ${arg_opt:-index1}.xslt $TMPFILE 2>/dev/null | sed '1d' >> $ITEMSFILE

(
  export BASEPATH;
  export ITEMSFILE;
  template2rss ${arg_opt:-index1}.xml | printContent "application/rss+xml"
  rm -f $ITEMSFILE
)

