#!/bin/sh
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.
#

local DATAPATH=$BASEPATH/app/tve
cd $DATAPATH

DATAFILE=$TMPFILE.data
ITEMSFILE=$TMPFILE.items
template="error.xml"

$MSDL -q -p http -o - "${arg_url}" > $TMPFILE

if grep 'flashvars' $TMPFILE > $DATAFILE; then
  xml_url=`cat $DATAFILE | sed 's-^.*xmlUrl=--;s-".*--;'`

  $MSDL -q -p http -o - "${xml_url}" > $TMPFILE

  $XSLTPROC --encoding utf-8 timeline.xslt $TMPFILE 2>/dev/null | sed '1d' >> $ITEMSFILE
  template="temp1.xml"
else
  $XSLTPROC --encoding utf-8 --html temp1.xslt $TMPFILE 2>/dev/null | sed '1d' >> $ITEMSFILE
  template="temp1.xml"
fi

rm $DATAFILE

(
  export BASEPATH;
  export ITEMSFILE;
  template2rss ${template} | printContent "application/rss+xml" 
  rm -f $ITEMSFILE
)

